spring:
  application:
    name: backend
  datasource:
    url: "jdbc:postgresql://localhost:5432/appdb"
    username: "devuser"
    password: "devpwd"
  jpa:
    hibernate:
      ddl-auto: none

  flyway:
    enabled: true

  logging:
    level:
      org.flywaydb: DEBUG